on:
  push:
    branches:
      - main
      - github-actions

name: Publish on push to main
jobs:
  publishDockerImage:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Login to Docker Registry
      uses: parkr/actions/docker-auth@main
      with:
        args: login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Build & publish
      uses: parkr/actions/docker-make@main
      with:
        args: docker-release -e REV=${{ github.sha }}
